### ISSUE TITLE
Implement interchangeable vocabulary

### ISSUE THREAD

**Issue by yurytsoy** [yurytsoy/hmeg#16]
The library should support various vocabulary. This can be useful for more focused learning (eg specific topic) and for progressing further in the language learning, when more complex vocabulary needs to be internalized.

# TODOs:
* [x] Create class `Vocabulary` for loading the vocabulary
* [x] Refactor `minilex` as `toml`-file
* [x] add methods:
    * `random_verb`
    * `random_noun`
    * `random_adjective`
    * `random_adverb`
* [x] update `ExerciseGenerator` to use custom vocabulary
* [x] add methods for registration of the custom vocabulary / extra vocabulary
* [x] add method for loading the vocabulary
* [x] add example for using built-in vocab => `minilex.toml`
* [x] add description of the vocabulary structure
* [ ] add example for extension
